site_name: LM Working Memory Test Suite
nav:
  - "Home": index.md
  - "API": api.md
plugins:
  mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        options:
          show_root_heading: false
          docstring_style: numpy