[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wm_suite"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = [
    "numpy == 1.21.2",
    "pandas == 1.2.4",
    "transformers == 4.6.1",
    "tqdm == 4.59.0",
    ]

[tool.setuptools.packages.find]
where = ["wm_suite"]

[project.scripts]
test_wm_suite = "test_package:check"