sbatch script_rnn_surprisal_sce1_repeat_random_lists.scr
sbatch script_rnn_surprisal_sce1_repeat_categorized_lists.scr
sbatch script_rnn_surprisal_sce1_permute_random_lists.scr
sbatch script_rnn_surprisal_sce1_permute_categorized_lists.scr
sbatch script_rnn_surprisal_sce1_control_random_lists.scr
sbatch script_rnn_surprisal_sce1_control_categorized_lists.scr
