sbatch script_rnn_surprisal_sce1_repeat_random.scr
sbatch script_rnn_surprisal_sce1_repeat_categorized.scr
sbatch script_rnn_surprisal_sce1_permute_random.scr
sbatch script_rnn_surprisal_sce1_permute_categorized.scr
sbatch script_rnn_surprisal_sce1_control_random.scr
sbatch script_rnn_surprisal_sce1_control_categorized.scr
