sbatch script_rnn_surprisal_sce1_repeat_categorized.scr
sbatch script_rnn_surprisal_sce1_permute_categorized.scr
sbatch script_rnn_surprisal_sce1_control_categorized.scr
sbatch script_rnn_surprisal_sce1rnd_repeat_categorized.scr
sbatch script_rnn_surprisal_sce1rnd_permute_categorized.scr
sbatch script_rnn_surprisal_sce1rnd_control_categorized.scr
